title: About Parallel
markdown: kramdown
theme: jekyll-theme-cayman

plugins:
  - jekyll-minifier

jekyll-minifier:
  uglifier_args:
    harmony: true

gtm_id: GTM-NLM5KSZ

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
  - README.md